package org.gamenet.indexv2

enum class Trigger {
    ON_TURN_BEGIN,
    ON_TURN_END,
    ON_PLAY,
    ON_TARGET_ENTER_BATTLEFIELD,
    ON_TARGET_ATTACKING,
    ON_TARGET_ATTACKED,
    ON_TARGET_KILLED,
    ON_TARGET_KILLING
}